---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: 0aaed7ac0a74b74d5fe0f0ac0289396f85985d48
    fabric8.io/iconUrl: img/icons/camel.svg
    fabric8.io/git-branch: main
  labels:
    expose: "true"
    app: i-ptg-test-item-list
    provider: fabric8
    version: 0.1.0
    group: com.redhat
  name: i-ptg-test-item-list
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: i-ptg-test-item-list
    provider: fabric8
    group: com.redhat
